apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gotd
  name: status
  labels:
    app: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8090'
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: bot
          image: ghcr.io/gotd/tgstatus:main
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
            initialDelaySeconds: 2
            periodSeconds: 3
          resources:
            requests:
              cpu: 250m
              memory: 128M
            limits:
              cpu: 250m
              memory: 128M
          env:
            - name: HOME
              value: /cache
            - name: HTTP_ADDR
              value: 0.0.0.0:8080
            - name: METRICS_ADDR
              value: 0.0.0.0:8090
          volumeMounts:
            - mountPath: /cache
              name: cache
