---
apiVersion: v1
kind: Service
metadata:
  namespace: gotd
  name: status
  labels:
    app: status
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: status
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: status
  name: status
  namespace: gotd
spec:
  virtualhost:
    fqdn: status.gotd.dev
  routes:
    - conditions:
        - prefix: /
      services:
        - name: status
          port: 80
