---
apiVersion: v1
kind: Service
metadata:
  namespace: gotd
  name: status
  labels:
    app: status
    prometheus: "true"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app: status
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status
  namespace: gotd
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: status
spec:
  rules:
  - host: status.gotd.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: status
            port:
              name: http
